### ISSUE TITLE
Support setting the parser type in the environment declaration

### ISSUE THREAD

**Issue by nbarrientos** [cernops/jens#6]
Something like this

```
---                                                                                                                    
default: master
notifications: foo@bar.com
parser: future
overrides:
  hostgroups:
    foo: a34
  modules: 
    bar: a44
```
With _current_ as default value.

https://docs.puppetlabs.com/puppet/3.8/reference/config_file_environment.html#parser
